spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task-manager?connectionTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  jackson:
    serialization:
      fail-on-self-references: false
  jdbc:
    initialize-schema: always
